import Foundation
import AppKit
import Combine
import CryptoKit

/// Polls `NSPasteboard.general.changeCount` every 250 ms and persists new clips.
/// This is the proven-by-Maccy approach: macOS provides no notification API
/// for clipboard changes, so polling is the only reliable mechanism.
@MainActor
final class PasteboardObserver: ObservableObject {
    @Published private(set) var isRunning: Bool = false
    @Published private(set) var lastChangeCount: Int = NSPasteboard.general.changeCount

    private let store: ClipStore
    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private let pollInterval: TimeInterval = 0.25

    init(store: ClipStore, pasteboard: NSPasteboard = .general) {
        self.store = store
        self.pasteboard = pasteboard
        start()
    }

    func start() {
        guard timer == nil else { return }
        isRunning = true
        // Prime so we don't capture whatever was on the clipboard before launch.
        lastChangeCount = pasteboard.changeCount

        let t = Timer(timeInterval: pollInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.tick() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        isRunning = false
    }

    private func tick() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        guard !SettingsStore.shared.isPaused else { return }
        guard !isTransient() else { return }
        if let bid = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
           SettingsStore.shared.ignoredBundleIds.contains(bid) {
            return
        }

        guard let item = buildClipItem() else { return }
        Task { @MainActor in
            do {
                try await store.insert(item)
                // 自動カテゴリ分類で振分先フォルダがあれば pin する。
                // インサート時点で id が確定しているように reloadInitial 後の
                // `store.recent.first` を新規クリップとみなす（同じハッシュなら
                // dedupe 済みなので問題なし）。
                if let inserted = store.recent.first {
                    AutoCategorizer.shared.tryAutoPin(clip: inserted, store: store)
                }
            } catch {
                NSLog("Pasty insert failed: \(error)")
            }
        }
    }

    /// Honour the system convention used by password managers: they mark
    /// pasteboard items as transient/concealed to ask history tools to skip.
    private func isTransient() -> Bool {
        let types = pasteboard.types ?? []
        let sensitiveRawValues: Set<String> = [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword"
        ]
        for type in types {
            if sensitiveRawValues.contains(type.rawValue) { return true }
        }
        return false
    }

    private func buildClipItem() -> ClipItem? {
        let now = Date()
        let frontApp = NSWorkspace.shared.frontmostApplication
        let bundleId = frontApp?.bundleIdentifier
        let appName = frontApp?.localizedName

        // 1) File URLs take priority over text representations of the same content.
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL],
           let url = urls.first {
            let isFile = url.isFileURL
            let preview = isFile ? url.lastPathComponent : url.absoluteString
            let size = Int64(url.absoluteString.utf8.count)
            var kind: ClipKind = isFile ? .file : .link
            // .file の場合のみ、拡張子で動画なら .video へ昇格。
            if kind == .file, Self.isVideoPath(url.absoluteString) {
                kind = .video
            }
            return ClipItem(
                id: nil,
                createdAt: now,
                kind: kind,
                preview: preview,
                content: url.absoluteString,
                dataPath: nil,
                byteSize: size,
                sourceBundleId: bundleId,
                sourceAppName: appName,
                contentHash: Self.sha256(url.absoluteString)
            )
        }

        // 2) Plain text / rich text.
        if let string = pasteboard.string(forType: .string) {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return nil }
            let preview = string.firstNonEmptyLine(limit: 120)
            var kind: ClipKind = pasteboard.data(forType: .rtf) != nil ? .richText : .text
            // テキストが http(s):// で始まる単一 URL のみで構成されているなら
            // .link に昇格させる(richText は維持)。
            if kind == .text,
               trimmed.range(of: #"^https?://\S+$"#, options: .regularExpression) != nil {
                kind = .link
            }
            return ClipItem(
                id: nil,
                createdAt: now,
                kind: kind,
                preview: preview,
                content: string,
                dataPath: nil,
                byteSize: Int64(string.utf8.count),
                sourceBundleId: bundleId,
                sourceAppName: appName,
                contentHash: Self.sha256(string)
            )
        }

        // 3) Images。PNG が直接来ていればそれを優先、無ければ TIFF を PNG に
        //    変換してから保存する。Finder / スクリーンショット / Slack の
        //    どれから来ても 1 つのコードパスで吸収できる。
        if let raw = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff) {
            let pngData = Self.pngData(from: raw) ?? raw
            let hash = Self.sha256Data(pngData)
            let rel = ClipBlobs.writeImage(pngData, hash: hash, suggestedExt: "png")
            let preview = "Image \(pngData.count.formattedBytes())"
            return ClipItem(
                id: nil,
                createdAt: now,
                kind: .image,
                preview: preview,
                content: nil,
                dataPath: rel,
                byteSize: Int64(pngData.count),
                sourceBundleId: bundleId,
                sourceAppName: appName,
                contentHash: hash
            )
        }

        return nil
    }

    /// ファイル URL / パス文字列の拡張子が動画なら true。
    private static func isVideoPath(_ pathOrURL: String) -> Bool {
        let lower = pathOrURL.lowercased()
        let exts = [".mov", ".mp4", ".m4v", ".mkv", ".avi", ".webm", ".mpg", ".mpeg"]
        return exts.contains(where: { lower.hasSuffix($0) })
    }

    private static func sha256(_ string: String) -> String {
        sha256Data(Data(string.utf8))
    }

    private static func sha256Data(_ data: Data) -> String {
        let digest = SHA256.hash(data: data)
        return digest.map { String(format: "%02x", $0) }.joined()
    }

    /// 与えられたデータを PNG に正規化。TIFF も PNG も Bitmap 経由で
    /// 同じ手順で吸収する。
    fileprivate static func pngData(from data: Data) -> Data? {
        guard let image = NSImage(data: data) else { return nil }
        guard let tiff = image.tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiff) else { return nil }
        return bitmap.representation(using: .png, properties: [:])
    }
}

extension NSPasteboard.PasteboardType {
    static let png = NSPasteboard.PasteboardType("public.png")
}

private extension String {
    func firstNonEmptyLine(limit: Int) -> String {
        for line in self.split(separator: "\n") {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if !trimmed.isEmpty {
                return String(trimmed.prefix(limit))
            }
        }
        return String(self.prefix(limit))
    }
}

private extension Int {
    func formattedBytes() -> String {
        let formatter = ByteCountFormatter()
        formatter.countStyle = .file
        return formatter.string(fromByteCount: Int64(self))
    }
}
